# Generated by Django 2.2.5 on 2019-10-03 00:06

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.Product._generar_ruta_imagen),
        ),
    ]
